services:
    proxy:
        image: nginx:latest
        restart: unless-stopped
        volumes:
            - ./proxy/default.conf.template:/etc/nginx/templates/default.conf.template
        ports:
            - '80:80'

    api:
        build: ./api
        restart: unless-stopped
        volumes:
            - ./api/src:/app/src
        environment:
            - PORT=80
        env_file:
            - .env # this is new

    frontend:
        build: ./frontend/timestamp-app
        restart: unless-stopped
        volumes:
            - ./frontend/timestamp-app/src:/app/src
        environment:
            - PORT=80

    database:
        image: mariadb:latest
        restart: unless-stopped
        ports:
            # Make the DB accessible from outside of the Docker network if needed
            - 3307:3306
        volumes:
            # Mount a volume for mariadb's persistent files for lifecycle outside of stack
            - './database/data:/var/lib/mysql'
            # Mount the db_schema directory into the container to be auto-read and created in the new db
            - './database/db_schema:/docker-entrypoint-initdb.d/users.sql'
        env_file:
            - .env
